### ISSUE TITLE
error: failed to run custom build command for `gitui v0.26.2 (/usr/src/RPM/BUILD/gitui-0.26.2)`

### ISSUE THREAD

**Issue by vt-alt** [extrawurst/gitui#2249]
**Describe the bug**
Build failure on v0.26.2.
```
23:55:10      Running `/usr/src/RPM/BUILD/gitui-0.26.2/target/release/build/gitui-4e6f46c82522e156/build-script-build`
23:55:10 error: failed to run custom build command for `gitui v0.26.2 (/usr/src/RPM/BUILD/gitui-0.26.2)`
23:55:10
23:55:10 Caused by:
23:55:10   process didn't exit successfully: `/usr/src/RPM/BUILD/gitui-0.26.2/target/release/build/gitui-4e6f46c82522e156/build-script-build` (exit status: 101)
23:55:10   --- stderr
23:55:10   thread 'main' panicked at build.rs:19:5:
23:55:10   Can not get git commit: No such file or directory (os error 2)
23:55:10   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Offline (no network access) build with a vendoring `cargo build -j20 --offline --release`.

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro: ALT Linux Sisyphus
 - GitUI Version: v0.26.2
 - Rust version: rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball)
 - cargo 1.78.0

**Comment by vt-alt** [comment]
And yes build is from `.src.rpm` (like a tarball), not from the git repo so there is no `.git` dir. I'd suggest you provide `get_git_hash` replacement with env var that we can set while building the package.

**Comment by extrawurst** [comment]
should be fixed via https://github.com/extrawurst/gitui/pull/2187/ right?

**Comment by vt-alt** [comment]
> should be fixed via #2187 right?

Looks good.

JFYI. When building RPM package from src.rpm (from RPM spec) there is still no commit id _by default_, so for downstream distributions it would be more handy to add rpm _release_ into it to identify the source. Currently I put `%release` rpm tag there so it looks like this (for `gitui-0.26.2-alt1`):
```
builder@x86_64:~$ gitui --version
gitui 0.26.2 2024-05-29 (alt1)
```

**Comment by hemedani** [comment]
I have the same error
```
error: failed to run custom build command for `gitui v0.26.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installteGXIB/release/build/gitui-a0d8ba9ca5b9f760/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/syd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gitui-0.26.3/build.rs:24:5:
  Can not get git commit: No such file or directory (os error 2)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `gitui v0.26.3`, intermediate artifacts can be found at `/tmp/cargo-installteGXIB`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
