### ISSUE TITLE
Segfault during push

### ISSUE THREAD

**Issue by 7system7** [extrawurst/gitui#2405]
**Describe the bug**
When I would like to push a commit, I got segmentation fault.

**To Reproduce**
1. Go to a git dir
2. Commit a message
3. Push the commit to the origin

**Expected behavior**
Push w/o crashing.

**Logs**
<details><summary>Journal logs</summary>
<p>

```bash
okt 25 13:02:35 AMANDA kernel: gitui[346571]: segfault at 73e830002308 ip 000073e830002308 sp 000073e8553fe8c8 error 15 likely on CPU 6 (core 12, socket 0)
okt 25 13:02:35 AMANDA kernel: Code: 00 00 00 00 00 00 00 00 00 00 c0 f5 3f 55 e8 73 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 00 00 05 00 00 00 <01> 44 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 01 00 01 00 91 01
okt 25 13:02:35 AMANDA systemd-coredump[346582]: Process 346539 (gitui) of user 1000 terminated abnormally with signal 11/SEGV, processing...
okt 25 13:02:35 AMANDA systemd[1]: Started Process Core Dump (PID 346582/UID 0).
okt 25 13:02:35 AMANDA systemd-coredump[346583]: [🡕] Process 346539 (gitui) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 346571:
                                                 #0  0x000073e830002308 n/a (n/a + 0x0)
                                                 #1  0x000073e85745ac5e n/a (libgit2.so.1.8 + 0xdfc5e)
                                                 #2  0x000073e85745b1d8 n/a (libgit2.so.1.8 + 0xe01d8)
                                                 #3  0x000073e8574624fa n/a (libgit2.so.1.8 + 0xe74fa)
                                                 #4  0x000073e8574649e6 n/a (libgit2.so.1.8 + 0xe99e6)
                                                 #5  0x000073e857468340 n/a (libgit2.so.1.8 + 0xed340)
                                                 #6  0x000073e857431759 git_remote_connect_ext (libgit2.so.1.8 + 0xb6759)
                                                 #7  0x000073e857436875 git_remote_upload (libgit2.so.1.8 + 0xbb875)
                                                 #8  0x000073e85743777f git_remote_push (libgit2.so.1.8 + 0xbc77f)
                                                 #9  0x000056efa4a158f7 n/a (gitui + 0x18f8f7)
                                                 #10 0x000056efa4a19654 n/a (gitui + 0x193654)
                                                 #11 0x000056efa4a1bebb n/a (gitui + 0x195ebb)
                                                 #12 0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #13 0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #14 0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346539:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4be3784 n/a (gitui + 0x35d784)
                                                 #2  0x000056efa4a9ad66 n/a (gitui + 0x214d66)
                                                 #3  0x000056efa49b8c63 n/a (gitui + 0x132c63)
                                                 #4  0x000056efa49b632a n/a (gitui + 0x13032a)
                                                 #5  0x000056efa4920fdc n/a (gitui + 0x9afdc)
                                                 #6  0x000056efa49ccb2c n/a (gitui + 0x146b2c)
                                                 #7  0x000073e856f6ee08 n/a (libc.so.6 + 0x25e08)
                                                 #8  0x000073e856f6eecc __libc_start_main (libc.so.6 + 0x25ecc)
                                                 #9  0x000056efa490be65 n/a (gitui + 0x85e65)
                                                 
                                                 Stack trace of thread 346542:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4b60632 n/a (gitui + 0x2da632)
                                                 #2  0x000056efa4906b37 n/a (gitui + 0x80b37)
                                                 #3  0x000056efa4b603a2 n/a (gitui + 0x2da3a2)
                                                 #4  0x000056efa4b60239 n/a (gitui + 0x2da239)
                                                 #5  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #6  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #7  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346541:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4b60632 n/a (gitui + 0x2da632)
                                                 #2  0x000056efa4906b37 n/a (gitui + 0x80b37)
                                                 #3  0x000056efa4b603a2 n/a (gitui + 0x2da3a2)
                                                 #4  0x000056efa4b60239 n/a (gitui + 0x2da239)
                                                 #5  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #6  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #7  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346545:
                                                 #0  0x000073e8570628b2 epoll_wait (libc.so.6 + 0x1198b2)
                                                 #1  0x000056efa4b2aa4d n/a (gitui + 0x2a4a4d)
                                                 #2  0x000056efa4a9f488 n/a (gitui + 0x219488)
                                                 #3  0x000056efa4aa19cc n/a (gitui + 0x21b9cc)
                                                 #4  0x000056efa491d982 n/a (gitui + 0x97982)
                                                 #5  0x000056efa49296ec n/a (gitui + 0xa36ec)
                                                 #6  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #7  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #8  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346543:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4b60632 n/a (gitui + 0x2da632)
                                                 #2  0x000056efa4906b37 n/a (gitui + 0x80b37)
                                                 #3  0x000056efa4b603a2 n/a (gitui + 0x2da3a2)
                                                 #4  0x000056efa4b60239 n/a (gitui + 0x2da239)
                                                 #5  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #6  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #7  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346575:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4be35d4 n/a (gitui + 0x35d5d4)
                                                 #2  0x000056efa49facff n/a (gitui + 0x174cff)
                                                 #3  0x000056efa4a12f1d n/a (gitui + 0x18cf1d)
                                                 #4  0x000056efa4a18860 n/a (gitui + 0x192860)
                                                 #5  0x000056efa4a1aed0 n/a (gitui + 0x194ed0)
                                                 #6  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #7  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #8  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 
                                                 Stack trace of thread 346544:
                                                 #0  0x000073e8570601fd syscall (libc.so.6 + 0x1171fd)
                                                 #1  0x000056efa4b60632 n/a (gitui + 0x2da632)
                                                 #2  0x000056efa4906b37 n/a (gitui + 0x80b37)
                                                 #3  0x000056efa4b603a2 n/a (gitui + 0x2da3a2)
                                                 #4  0x000056efa4b60239 n/a (gitui + 0x2da239)
                                                 #5  0x000056efa4c1c9cb n/a (gitui + 0x3969cb)
                                                 #6  0x000073e856fdd39d n/a (libc.so.6 + 0x9439d)
                                                 #7  0x000073e85706249c n/a (libc.so.6 + 0x11949c)
                                                 ELF object binary architecture: AMD x86-64
```

</p>
</details> 

**Context (please complete the following information):**
 - OS/Distro + Version: Arch linux, rolling release
 - GitUI Version gitui nightly 2024-09-12 (0f5cf89)

**Additional context**
#### Software version

gitui 0.26.3 (v0.19.0-789-g0f5cf893)

#### Operating system

Linux 6.11.5-arch1-1

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-gnu
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Environment variables

```bash
SHELL=/bin/bash
EDITOR=/usr/bin/nano
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
gitui --bugreport 
```

**Comment by extrawurst** [comment]
probably caused by upstream: https://github.com/libgit2/libgit2/issues/6930

**Comment by ethomson** [comment]
One would indeed imagine that this is related, but nothing changed in our networking stack between v1.8.1 and v1.8.2. 

Since this is actually dying in http-parser, this is _probably_ related to the change we made to allow users to opt in to llhttp. But I’m surprised that this didn’t crop up in v1.8.1.

Any chance you could capture a dump?

**Comment by elbertronnie** [comment]
I have been getting a segfault when I tried to pull a branch. I feel like this is the same crash that happened when pushing a branch. Here is a backtrace of the coredumped file:

```
[elbert@arch ~]$ coredumpctl gdb -1
           PID: 2732 (gitui)
           UID: 1000 (elbert)
           GID: 1000 (elbert)
        Signal: 11 (SEGV)
     Timestamp: Sun 2024-10-27 07:53:06 IST (19min ago)
  Command Line: gitui
    Executable: /usr/bin/gitui
 Control Group: /user.slice/user-1000.slice/user@1000.service/kitty-1399-0.scope
          Unit: user@1000.service
     User Unit: kitty-1399-0.scope
         Slice: user-1000.slice
     Owner UID: 1000 (elbert)
       Boot ID: 772192f3c52a4b3bae171a69dfe43625
    Machine ID: f27852a2666741a1bb13e3059bbc2b7d
      Hostname: arch
       Storage: /var/lib/systemd/coredump/core.gitui.1000.772192f3c52a4b3bae171a69dfe43625.2732.1729995786000000.zst (present)
  Size on Disk: 1.5M
       Message: Process 2732 (gitui) of user 1000 dumped core.
                
                Stack trace of thread 2733:
                #0  0x000074c3f0013908 n/a (n/a + 0x0)
                #1  0x000074c3f50b9c5e n/a (libgit2.so.1.8 + 0xdfc5e)
                #2  0x000074c3f50ba1d8 n/a (libgit2.so.1.8 + 0xe01d8)
                #3  0x000074c3f50c14fa n/a (libgit2.so.1.8 + 0xe74fa)
                #4  0x000074c3f50c39e6 n/a (libgit2.so.1.8 + 0xe99e6)
                #5  0x000074c3f50c7340 n/a (libgit2.so.1.8 + 0xed340)
                #6  0x000074c3f5090759 git_remote_connect_ext (libgit2.so.1.8 + 0xb6759)
                #7  0x000074c3f5093c1e git_remote_fetch (libgit2.so.1.8 + 0xb9c1e)
                #8  0x00005f0740561bb1 n/a (gitui + 0x195bb1)
                #9  0x00005f074048b7dd n/a (gitui + 0xbf7dd)
                #10 0x00005f074044cc0b n/a (gitui + 0x80c0b)
                #11 0x00005f07406a63a2 n/a (gitui + 0x2da3a2)
                #12 0x00005f07406a6239 n/a (gitui + 0x2da239)
                #13 0x00005f07407629cb n/a (gitui + 0x3969cb)
                #14 0x000074c3f4c3b39d n/a (libc.so.6 + 0x9439d)
                #15 0x000074c3f4cc049c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 2732:
                #0  0x000074c3f4cbe1fd syscall (libc.so.6 + 0x1171fd)
                #1  0x00005f0740729784 n/a (gitui + 0x35d784)
                #2  0x00005f07405e0d66 n/a (gitui + 0x214d66)
                #3  0x00005f07404fec63 n/a (gitui + 0x132c63)
                #4  0x00005f07404fc32a n/a (gitui + 0x13032a)
                #5  0x00005f0740466fdc n/a (gitui + 0x9afdc)
                #6  0x00005f0740512b2c n/a (gitui + 0x146b2c)
                #7  0x000074c3f4bcce08 n/a (libc.so.6 + 0x25e08)
                #8  0x000074c3f4bccecc __libc_start_main (libc.so.6 + 0x25ecc)
                #9  0x00005f0740451e65 n/a (gitui + 0x85e65)
                
                Stack trace of thread 2734:
                #0  0x000074c3f4cbe1fd syscall (libc.so.6 + 0x1171fd)
                #1  0x00005f07406a6632 n/a (gitui + 0x2da632)
                #2  0x00005f074044cb37 n/a (gitui + 0x80b37)
                #3  0x00005f07406a63a2 n/a (gitui + 0x2da3a2)
                #4  0x00005f07406a6239 n/a (gitui + 0x2da239)
                #5  0x00005f07407629cb n/a (gitui + 0x3969cb)
                #6  0x000074c3f4c3b39d n/a (libc.so.6 + 0x9439d)
                #7  0x000074c3f4cc049c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 2735:
                #0  0x000074c3f4cbe1fd syscall (libc.so.6 + 0x1171fd)
                #1  0x00005f07406a6632 n/a (gitui + 0x2da632)
                #2  0x00005f074044cb37 n/a (gitui + 0x80b37)
                #3  0x00005f07406a63a2 n/a (gitui + 0x2da3a2)
                #4  0x00005f07406a6239 n/a (gitui + 0x2da239)
                #5  0x00005f07407629cb n/a (gitui + 0x3969cb)
                #6  0x000074c3f4c3b39d n/a (libc.so.6 + 0x9439d)
                #7  0x000074c3f4cc049c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 2736:
                #0  0x000074c3f4cbe1fd syscall (libc.so.6 + 0x1171fd)
                #1  0x00005f07406a6632 n/a (gitui + 0x2da632)
                #2  0x00005f074044cb37 n/a (gitui + 0x80b37)
                #3  0x00005f07406a63a2 n/a (gitui + 0x2da3a2)
                #4  0x00005f07406a6239 n/a (gitui + 0x2da239)
                #5  0x00005f07407629cb n/a (gitui + 0x3969cb)
                #6  0x000074c3f4c3b39d n/a (libc.so.6 + 0x9439d)
                #7  0x000074c3f4cc049c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 2737:
                #0  0x000074c3f4cc08b2 epoll_wait (libc.so.6 + 0x1198b2)
                #1  0x00005f0740670a4d n/a (gitui + 0x2a4a4d)
                #2  0x00005f07405e5488 n/a (gitui + 0x219488)
                #3  0x00005f07405e79cc n/a (gitui + 0x21b9cc)
                #4  0x00005f0740463982 n/a (gitui + 0x97982)
                #5  0x00005f074046f6ec n/a (gitui + 0xa36ec)
                #6  0x00005f07407629cb n/a (gitui + 0x3969cb)
                #7  0x000074c3f4c3b39d n/a (libc.so.6 + 0x9439d)
                #8  0x000074c3f4cc049c n/a (libc.so.6 + 0x11949c)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/gitui...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Reading symbols from /home/elbert/.cache/debuginfod_client/1055dfbad5d19b51733b2946b470a508763142bc/debuginfo...
(No debugging symbols found in /home/elbert/.cache/debuginfod_client/1055dfbad5d19b51733b2946b470a508763142bc/debuginfo)
[New LWP 2733]
[New LWP 2732]
[New LWP 2734]
[New LWP 2735]
[New LWP 2736]
[New LWP 2737]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `gitui'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000074c3f0013908 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
[Current thread is 1 (Thread 0x74c3f45c56c0 (LWP 2733))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/bin/gitui.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  0x000074c3f0013908 in ?? ()
#1  0x000074c3f4b9e464 in http_parser_execute (parser=parser@entry=0x74c3f0013908, settings=settings@entry=0x74c3f45c39e0, data=<optimized out>, len=<optimized out>)
    at /usr/src/debug/http-parser/http-parser-2.9.4/http_parser.c:908
#2  0x000074c3f50b7ff2 in git_http_parser_execute (parser=parser@entry=0x74c3f0013908, data=<optimized out>, len=<optimized out>)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/httpparser.c:82
#3  0x000074c3f50b9c5e in client_read_and_parse (client=client@entry=0x74c3f00138e0) at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/httpclient.c:1178
#4  0x000074c3f50ba1d8 in git_http_client_read_response (response=response@entry=0x74c3f45c3b90, client=0x74c3f00138e0)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/httpclient.c:1458
#5  0x000074c3f50c14fa in http_stream_read (s=0x74c3f005ca10, buffer=0x74c3f00753d8 "", buffer_size=65536, out_len=0x74c3f45c3cf0)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/http.c:427
#6  0x000074c3f50c39e6 in git_smart__recv (t=t@entry=0x74c3f00751b0) at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/smart.c:29
#7  0x000074c3f50c7340 in git_smart__store_refs (t=0x74c3f00751b0, flushes=2) at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/smart_protocol.c:58
#8  git_smart__connect (transport=0x74c3f00751b0, url=<optimized out>, direction=<optimized out>, connect_opts=<optimized out>)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/transports/smart.c:171
#9  0x000074c3f5090759 in git_remote_connect_ext (remote=remote@entry=0x74c3f000a720, direction=direction@entry=GIT_DIRECTION_FETCH, 
    given_opts=given_opts@entry=0x74c3f45c3f90) at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/remote.c:963
#10 0x000074c3f5093c1e in connect_or_reset_options (remote=0x74c3f000a720, direction=0, opts=0x74c3f45c3f90)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/remote.c:1254
#11 git_remote_fetch (remote=0x74c3f000a720, refspecs=0x74c3f45c4240, opts=0x74c3f45c4170, reflog_message=0x0)
    at /usr/src/debug/libgit2/libgit2-1.8.2/src/libgit2/remote.c:1375
#12 0x00005f0740561bb1 in git2::remote::Remote::fetch ()
#13 0x00005f074048b7dd in <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute ()
#14 0x00005f074044cc0b in rayon_core::registry::WorkerThread::wait_until_cold ()
#15 0x00005f07406a63a2 in std::sys::backtrace::__rust_begin_short_backtrace ()
#16 0x00005f07406a6239 in core::ops::function::FnOnce::call_once{{vtable.shim}} ()
#17 0x00005f07407629cb in std::sys::pal::unix::thread::Thread::new::thread_start ()
#18 0x000074c3f4c3b39d in start_thread (arg=<optimized out>) at pthread_create.c:447
#19 0x000074c3f4cc049c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by ethomson** [comment]
We think that the libgit2 issue is fixed in v1.8.3.

**Comment by 7system7** [comment]
Yeah, I forgot to add the coredump. It seems similar.

<details><summary>Details</summary>
<p>

```bash
coredumpctl gdb -1                                                                                                                                                                                                                                                     ─╯
           PID: 663436 (gitui)
           UID: 1000 (system7)
           GID: 984 (users)
        Signal: 11 (SEGV)
     Timestamp: Fri 2024-10-25 19:55:19 CEST (1 day 14h ago)
  Command Line: gitui
    Executable: /usr/bin/gitui
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/vte-spawn-72bb1fcd-5976-4619-ba38-6789b2430d24.scope
          Unit: user@1000.service
     User Unit: vte-spawn-72bb1fcd-5976-4619-ba38-6789b2430d24.scope
         Slice: user-1000.slice
     Owner UID: 1000 (system7)
       Boot ID: c243156ded10457bbbdcc94fa060e4c4
    Machine ID: e2e6bd0fa41d489aa22ed602e2b5522c
      Hostname: AMANDA
       Storage: /var/lib/systemd/coredump/core.gitui.1000.c243156ded10457bbbdcc94fa060e4c4.663436.1729878919000000.zst (present)
  Size on Disk: 1.1M
       Message: Process 663436 (gitui) of user 1000 dumped core.
                
                Stack trace of thread 663437:
                #0  0x00007fc3e8011998 n/a (n/a + 0x0)
                #1  0x00007fc3fdee4c5e n/a (libgit2.so.1.8 + 0xdfc5e)
                #2  0x00007fc3fdee51d8 n/a (libgit2.so.1.8 + 0xe01d8)
                #3  0x00007fc3fdeec4fa n/a (libgit2.so.1.8 + 0xe74fa)
                #4  0x00007fc3fdeee9e6 n/a (libgit2.so.1.8 + 0xe99e6)
                #5  0x00007fc3fdef2340 n/a (libgit2.so.1.8 + 0xed340)
                #6  0x00007fc3fdebb759 git_remote_connect_ext (libgit2.so.1.8 + 0xb6759)
                #7  0x00007fc3fdebbbcd git_remote_connect (libgit2.so.1.8 + 0xb6bcd)
                #8  0x000056ec9adfa770 n/a (gitui + 0x18e770)
                #9  0x000056ec9ad3087b n/a (gitui + 0xc487b)
                #10 0x000056ec9acecc0b n/a (gitui + 0x80c0b)
                #11 0x000056ec9af463a2 n/a (gitui + 0x2da3a2)
                #12 0x000056ec9af46239 n/a (gitui + 0x2da239)
                #13 0x000056ec9b0029cb n/a (gitui + 0x3969cb)
                #14 0x00007fc3fda6639d n/a (libc.so.6 + 0x9439d)
                #15 0x00007fc3fdaeb49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 663436:
                #0  0x00007fc3fdae91fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000056ec9afc9784 n/a (gitui + 0x35d784)
                #2  0x000056ec9ae80d66 n/a (gitui + 0x214d66)
                #3  0x000056ec9ad9ec63 n/a (gitui + 0x132c63)
                #4  0x000056ec9ad9c32a n/a (gitui + 0x13032a)
                #5  0x000056ec9ad06fdc n/a (gitui + 0x9afdc)
                #6  0x000056ec9adb2b2c n/a (gitui + 0x146b2c)
                #7  0x00007fc3fd9f7e08 n/a (libc.so.6 + 0x25e08)
                #8  0x00007fc3fd9f7ecc __libc_start_main (libc.so.6 + 0x25ecc)
                #9  0x000056ec9acf1e65 n/a (gitui + 0x85e65)
                
                Stack trace of thread 663439:
                #0  0x00007fc3fdae91fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000056ec9af46632 n/a (gitui + 0x2da632)
                #2  0x000056ec9acecb37 n/a (gitui + 0x80b37)
                #3  0x000056ec9af463a2 n/a (gitui + 0x2da3a2)
                #4  0x000056ec9af46239 n/a (gitui + 0x2da239)
                #5  0x000056ec9b0029cb n/a (gitui + 0x3969cb)
                #6  0x00007fc3fda6639d n/a (libc.so.6 + 0x9439d)
                #7  0x00007fc3fdaeb49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 663440:
                #0  0x00007fc3fdae91fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000056ec9af46632 n/a (gitui + 0x2da632)
                #2  0x000056ec9acecb37 n/a (gitui + 0x80b37)
                #3  0x000056ec9af463a2 n/a (gitui + 0x2da3a2)
                #4  0x000056ec9af46239 n/a (gitui + 0x2da239)
                #5  0x000056ec9b0029cb n/a (gitui + 0x3969cb)
                #6  0x00007fc3fda6639d n/a (libc.so.6 + 0x9439d)
                #7  0x00007fc3fdaeb49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 663441:
                #0  0x00007fc3fdaeb8b2 epoll_wait (libc.so.6 + 0x1198b2)
                #1  0x000056ec9af10a4d n/a (gitui + 0x2a4a4d)
                #2  0x000056ec9ae85488 n/a (gitui + 0x219488)
                #3  0x000056ec9ae879cc n/a (gitui + 0x21b9cc)
                #4  0x000056ec9ad03982 n/a (gitui + 0x97982)
                #5  0x000056ec9ad0f6ec n/a (gitui + 0xa36ec)
                #6  0x000056ec9b0029cb n/a (gitui + 0x3969cb)
                #7  0x00007fc3fda6639d n/a (libc.so.6 + 0x9439d)
                #8  0x00007fc3fdaeb49c n/a (libc.so.6 + 0x11949c)
                
                Stack trace of thread 663438:
                #0  0x00007fc3fdae91fd syscall (libc.so.6 + 0x1171fd)
                #1  0x000056ec9af46632 n/a (gitui + 0x2da632)
                #2  0x000056ec9acecb37 n/a (gitui + 0x80b37)
                #3  0x000056ec9af463a2 n/a (gitui + 0x2da3a2)
                #4  0x000056ec9af46239 n/a (gitui + 0x2da239)
                #5  0x000056ec9b0029cb n/a (gitui + 0x3969cb)
                #6  0x00007fc3fda6639d n/a (libc.so.6 + 0x9439d)
                #7  0x00007fc3fdaeb49c n/a (libc.so.6 + 0x11949c)
                ELF object binary architecture: AMD x86-64

Failed to invoke gdb: No such file or directory
```

</p>
</details>
